/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Will
 */
public class FormCompra extends javax.swing.JFrame {

    /**
     * Creates new form FormCompra
     */
    public FormCompra() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        titulo = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        optEx = new javax.swing.JRadioButton();
        optElx = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        opt4p = new javax.swing.JRadioButton();
        opt2p = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        optPag = new javax.swing.JCheckBox();
        inputQtd = new javax.swing.JSpinner();
        jPanel4 = new javax.swing.JPanel();
        optAir = new javax.swing.JCheckBox();
        optAr = new javax.swing.JCheckBox();
        optTrava = new javax.swing.JCheckBox();
        optRadio = new javax.swing.JCheckBox();
        labelValor = new javax.swing.JLabel();
        btnCalc = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Compra");
        setBackground(new java.awt.Color(102, 102, 102));
        getContentPane().setLayout(null);

        titulo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        titulo.setToolTipText("titulo");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Modelo"));

        buttonGroup1.add(optEx);
        optEx.setText("EX");
        optEx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optExActionPerformed(evt);
            }
        });

        buttonGroup1.add(optElx);
        optElx.setText("ELX CD");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(optEx)
                    .addComponent(optElx))
                .addGap(0, 25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(optEx)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(optElx))
        );

        optEx.getAccessibleContext().setAccessibleName("optEx");
        optElx.getAccessibleContext().setAccessibleName("optElx");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Portas"));

        buttonGroup2.add(opt4p);
        opt4p.setText("4p");

        buttonGroup2.add(opt2p);
        opt2p.setText("2p");
        opt2p.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt2pActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(opt2p)
                    .addComponent(opt4p))
                .addGap(0, 47, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(opt2p)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(opt4p)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        opt4p.getAccessibleContext().setAccessibleName("opt4p");
        opt2p.getAccessibleContext().setAccessibleName("opt2p");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Opções"));

        jLabel2.setText("Qntd:");

        optPag.setText("Pagt. à vista");
        optPag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optPagActionPerformed(evt);
            }
        });

        inputQtd.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(inputQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(optPag, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inputQtd, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(optPag)
                .addGap(24, 24, 24))
        );

        optPag.getAccessibleContext().setAccessibleName("optPag");

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Acessórios Opcionais"));

        optAir.setText("Air Bag");
        optAir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optAirActionPerformed(evt);
            }
        });

        optAr.setText("Ar Condicionado");
        optAr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optArActionPerformed(evt);
            }
        });

        optTrava.setText("Trava Elétrica");
        optTrava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optTravaActionPerformed(evt);
            }
        });

        optRadio.setText("Rádio/ CD");
        optRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optRadioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(optAir, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(optAr)
                    .addComponent(optTrava, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(optRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(optAir)
                .addGap(18, 18, 18)
                .addComponent(optAr)
                .addGap(18, 18, 18)
                .addComponent(optTrava)
                .addGap(18, 18, 18)
                .addComponent(optRadio)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        optAir.getAccessibleContext().setAccessibleName("OptAir");
        optAr.getAccessibleContext().setAccessibleName("optAr");
        optTrava.getAccessibleContext().setAccessibleName("optTrava");
        optRadio.getAccessibleContext().setAccessibleName("optRadio");

        labelValor.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelValor.setText("VALOR");

        javax.swing.GroupLayout tituloLayout = new javax.swing.GroupLayout(titulo);
        titulo.setLayout(tituloLayout);
        tituloLayout.setHorizontalGroup(
            tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tituloLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tituloLayout.createSequentialGroup()
                        .addComponent(labelValor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(21, 21, 21))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51))
        );
        tituloLayout.setVerticalGroup(
            tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tituloLayout.createSequentialGroup()
                .addGroup(tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tituloLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tituloLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelValor, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(88, Short.MAX_VALUE))
        );

        getContentPane().add(titulo);
        titulo.setBounds(10, 10, 470, 450);
        titulo.getAccessibleContext().setAccessibleName("");
        titulo.getAccessibleContext().setAccessibleDescription("");

        btnCalc.setBackground(new java.awt.Color(204, 204, 204));
        btnCalc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botaCalc.jpg"))); // NOI18N
        btnCalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalc);
        btnCalc.setBounds(510, 90, 90, 110);

        setSize(new java.awt.Dimension(677, 539));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void optAirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optAirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_optAirActionPerformed

    private void optArActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optArActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_optArActionPerformed

    private void optTravaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optTravaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_optTravaActionPerformed

    private void optRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_optRadioActionPerformed

    private void optPagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optPagActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_optPagActionPerformed

    private void btnCalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcActionPerformed
        // TODO add your handling code here:
        int qtd=0;
        float preco=0;
        qtd = Integer.parseInt(inputQtd.getValue().toString());
        if(optEx.isSelected() && opt2p.isSelected()){
            preco=14021;
        }
        else if(optEx.isSelected() && opt4p.isSelected()){
            preco=15107;
        }
        else if(optElx.isSelected() && opt2p.isSelected()){
            preco=16235;
        }
        else if(optElx.isSelected() && opt4p.isSelected()){
            preco=17450;
        }
        if (optAir.isSelected()){
           preco = preco + 150;
        }else{preco=preco;}
        
        if (optAr.isSelected()){
           preco = preco + 2170;
        }else{preco=preco;}
        
        if (optTrava.isSelected()){
           preco = preco + 400;
        }else{preco=preco;}
        
        if (optRadio.isSelected()){
           preco = preco + 550;
        }else{preco=preco;}
        
        if(qtd>0){
            preco = preco*qtd;
        }else{preco =preco*qtd;}
        
        if(optPag.isSelected()){
            preco = (float)(preco*0.9);
        }else{preco=preco;}
        if (preco==0){
            labelValor.setText("Nenhuma opção selecionada");
        } 
        else{
            labelValor.setText("VALOR:R$ "+preco);
        }
    }//GEN-LAST:event_btnCalcActionPerformed

    private void optExActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optExActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_optExActionPerformed

    private void opt2pActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt2pActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opt2pActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCompra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalc;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JSpinner inputQtd;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel labelValor;
    private javax.swing.JRadioButton opt2p;
    private javax.swing.JRadioButton opt4p;
    private javax.swing.JCheckBox optAir;
    private javax.swing.JCheckBox optAr;
    private javax.swing.JRadioButton optElx;
    private javax.swing.JRadioButton optEx;
    private javax.swing.JCheckBox optPag;
    private javax.swing.JCheckBox optRadio;
    private javax.swing.JCheckBox optTrava;
    private javax.swing.JPanel titulo;
    // End of variables declaration//GEN-END:variables
}
